```{r}
cars
```

```{r}
head(cars)
```

```{r}
scatter.smooth(x=cars$speed, y=cars$dist, main="Dist ~ Speed")
```

```{r}
par(mfrow=c(1, 2))
```
```{r}
boxplot(cars$speed, main="Speed", sub=paste("Outlier rows: ",boxplot.stats(cars$speed)$out))
```

```{r}
boxplot(cars$dist, main="Distance", sub=paste("Outlier rows: ",boxplot.stats(cars$dist)$out))
```

```{r}
library(e1071)
```

```{r}
par(mfrow=c(1, 2))
```
```{r}
plot(density(cars$speed), main="Density Plot: Speed",ylab="Frequency",sub=paste("Skewness:",round(e1071::skewness(cars$speed),2)))
polygon(density(cars$speed), col="red")
plot(density(cars$dist), main="Density Plot: Distance", ylab = "Frequency", sub=paste("Skewness:", round(e1071::skewness(cars$dist), 2)))
polygon(density(cars$dist), col="red")

```
```{r}
cor(cars$speed, cars$dist)
```

```{r}
linearMod <- lm(dist ~ speed, data=cars)
print(linearMod)
```
```{r}
summary(linearMod)
```

```{r}
modelSummary <- summary(linearMod)
print(modelSummary)
```

```{r}
modelCoeffs <- modelSummary$coefficients
print(modelCoeffs)
```
```{r}
beta.estimate <- modelCoeffs["speed", "Estimate"] 
print(beta.estimate)
```
```{r}
std.error <- modelCoeffs["speed", "Std. Error"]
print(std.error)
```
```{r}
t_value <- beta.estimate/std.error
print(t_value)
```
```{r}
p_value <- 2*pt(-abs(t_value), df=nrow(cars)-ncol(cars))
print(p_value)
```
```{r}
f_statistic <- linearMod$fstatistic[1]
print(f_statistic)
```

```{r}
f <- summary(linearMod)$fstatistic
model_p <- pf(f[1], f[2], f[3], lower=FALSE)
AIC(linearMod)
```

```{r}
BIC(linearMod)
```

```{r}
set.seed(100)
trainingRowIndex <- sample(1:nrow(cars), 0.8*nrow(cars))
trainingData <- cars[trainingRowIndex, ]
testData  <- cars[-trainingRowIndex, ]
lmMod <- lm(dist ~ speed, data=trainingData)
distPred <- predict(lmMod, testData)
summary (lmMod)

```

```{r}
actuals_preds <- data.frame(cbind(actuals=testData$dist,predicteds=distPred))
correlation_accuracy <- cor(actuals_preds)
print(correlation_accuracy)
```
```{r}
head(actuals_preds)
```

